Connected to MySQL Server:  5.5.5-10.4.27-MariaDB
Login
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\FCPC OJT DEV\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\FCPC OJT DEV\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\xampp\htdocs\SMART-ID-REGISTRATION-MODULE-v2\main.py", line 216, in search
    i = search_result[0]
        ~~~~~~~~~~~~~^^^
IndexError: list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\FCPC OJT DEV\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\FCPC OJT DEV\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\xampp\htdocs\SMART-ID-REGISTRATION-MODULE-v2\main.py", line 216, in search
    i = search_result[0]
        ~~~~~~~~~~~~~^^^
IndexError: list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\FCPC OJT DEV\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\FCPC OJT DEV\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\xampp\htdocs\SMART-ID-REGISTRATION-MODULE-v2\main.py", line 216, in search
    i = search_result[0]
        ~~~~~~~~~~~~~^^^
IndexError: list index out of range
